### ISSUE TITLE
Can it be effectively used in a library project?

### ISSUE THREAD

**Issue by Buckstabue** [HujiangTechnology/gradle_plugin_android_aspectjx#10]
I want to create a common error handler for a library class by means of your plugin. Is it possible at all? Can I do it without too much affecting client code, I mean if I do so, will client code be able to use instant run and other features?

**Comment by firefly1126** [comment]
No, I will add this feature later

**Comment by johnsonyuw** [comment]
does it fixed now?

**Comment by johnsonyuw** [comment]
aspectjx {
	includeJarFilter 'appname/submodulename'
}

@Pointcut("execution(* android.view.View.OnClickListener.onClick(..))"
    )
    public void clickEvent() {
        Log.e(TAG, "===CLICK===6 clickEvent");
    }

i tried like this,  the method in submodulename not work.

**Comment by johnsonyuw** [comment]
finally i used hugo instead to fix it.
