### ISSUE TITLE
as点击运行时报错 希望楼主给看下

### ISSUE THREAD

**Issue by Alembertcn** [HujiangTechnology/gradle_plugin_android_aspectjx#100]
根目录
 dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.0'
    }

model目录
apply plugin: 'com.android.application'
apply plugin: 'android-aspectjx'
dependencies {
    implementation 'org.aspectj:aspectjrt:1.8.9'
}

Caused by: java.io.IOException: Failed to read zip file 'C:\Users\*****\app\build\intermediates\transforms\ajx\debug\13.jar'.

**Comment by zmobs** [comment]
一样的问题。。没人给解决了摸

**Comment by shenhualongg** [comment]
一样的问题，xx.jar的xx不固定

**Comment by shenhualongg** [comment]
请问有解决方案么？

**Comment by delingli** [comment]
都遇到了这个问题，但是没人鸟啊，mmp不如不用
