### ISSUE TITLE
您好，首先感谢您的开源贡献。我提个issue吧（奸诈表情） androidstudio环境 android tools 3.1.3 gradle4.4 

### ISSUE THREAD

**Issue by Xiasm** [HujiangTechnology/gradle_plugin_android_aspectjx#101]
androidstudio3.1.3 
android tools 3.1.3 
gradle4.4 

编译不报错，运行就报错。
报错1：EOCD signature not found in the last 0 bytes of the file. 
报错2：Caused by: java.io.IOException: Failed to read zip file 'D:\WorkSpace\project\yongche-android\app\build\intermediates\transforms\ajx\production\debug\91.jar'.

**Comment by Xiasm** [comment]
@Alembertcn  如果是新建的项目，没有这个问题，用到老项目上就会出现这个问题，怀疑和其他插件有冲突

**Comment by qinbode** [comment]
用android studio 2.3 报pre-dex错误
用android studio 3.1 报EOCD signature not found in the last 0 bytes of the file错误
我是不是该直接用aspectj算了

**Comment by zmobs** [comment]
我这里也遇到了同样的问题。  gradle 4.1   buildTool 3.0.1

**Comment by CodeIdeal** [comment]
大多数情况都是自己的pointcut写的有问题

**Comment by dotcink** [comment]
@CodeIdeal 我这里 Pointcut 写错会报这个错，如果报的错能详细点就好了。

**Comment by Nullifier1571** [comment]
所以这个怎么解？我把build下边全删了都不行。 @Around("methodAnnotatedWithDebugTrace()")可以， @Before("methodAnnotatedWithDebugTrace()")不行

**Comment by 792814781** [comment]
我也遇到同样的问题，设置了JavaVersion 1.8 后就这样：
`compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
`
改成1.7就能编译通过。

**Comment by xuIcream** [comment]
我也碰到了 有解决了么

**Comment by protectedMan** [comment]
这个库和instant run冲突哦

**Comment by KwanTang324** [comment]
一样 不知道如何解决

**Comment by larrySmile02** [comment]
检查一下被注释的方法是否public

@around(xxxxxx)
public void foo(JointPoint jp){
...
}
如果方法是private就会报错。

**Comment by flyinghero2009** [comment]
一样的问题，其他同事编译运行都没有问题，只有我的运行报该错误
