### ISSUE TITLE
2.0.1版本的exclude根据包名过滤文件无效

### ISSUE THREAD

**Issue by ChenWei-Store** [HujiangTechnology/gradle_plugin_android_aspectjx#103]
我当前的项目结构是一个主project，一个module，在主project中使用了aspectJ，现在想排除module，不在module中插入代码。而我在主project的app目录下的build文件中声明了下面代码，其中aa.bb.cc是module包名
`
aspectjx {
exclude 'aa.bb.cc'
}
`
不知道为什么并没有过滤掉

**Comment by idis573** [comment]
问题解决。比如包名com.test

在windows下ranEntryName是com/test
在mac下ranEntryName是com.test

所以过滤条件需写成include 'com.test','com/test' 或者直接include 'test'。

同理exclude也是
