### ISSUE TITLE
2.0.1版本的include根据包名过滤文件无效

### ISSUE THREAD

**Issue by idis573** [HujiangTechnology/gradle_plugin_android_aspectjx#108]
include 加进来的包名无效，inputfile打印出来只有一行，实际上应该有好几个jar

**Comment by idis573** [comment]
问题解决。比如包名com.test

在windows下ranEntryName是com/test
在mac下ranEntryName是com.test

所以过滤条件需写成include 'com.test','com/test' 或者直接include 'test'

**Comment by longforus** [comment]
@idis573  哥们儿太6了,完美解决了我的问题
@HujiangTech  ,希望作者能够加入到readme中.
