### ISSUE TITLE
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.

### ISSUE THREAD

**Issue by penghongru** [HujiangTechnology/gradle_plugin_android_aspectjx#109]
Android studio 3.1.3
在module中apply plugin: 'android-aspectjx'

编译警告 Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.

建议将plugin中的 cpmpile 替换为 api

**Comment by flyou** [comment]
溜了 溜了还是直接用aspectj靠谱
