### ISSUE TITLE
疑对kotlin支持不足，在object 对象中有方法，被aspectj织入代码并混淆后会出现ClassCastException这样的错误。

### ISSUE THREAD

**Issue by x930073498** [HujiangTechnology/gradle_plugin_android_aspectjx#115]
![image](https://user-images.githubusercontent.com/16031755/45216561-9d32dd00-b2d3-11e8-95e1-5114bb5e068b.png)

![image](https://user-images.githubusercontent.com/16031755/45216395-0c5c0180-b2d3-11e8-9c56-2622663a15db.png)
![image](https://user-images.githubusercontent.com/16031755/45216520-81c7d200-b2d3-11e8-82e6-bc5bb69665b4.png)
![image](https://user-images.githubusercontent.com/16031755/45216648-ed11a400-b2d3-11e8-9534-ef7c868dcc64.png)

**Comment by firefly1126** [comment]
这个不是对kotlin支持的问题，而且ClassCastException的问题和混淆没有关系，你应该排除其他干扰因素去定位问题，在debug环境下去定位一下问题吧。

**Comment by x930073498** [comment]
我这边不开混淆的话就没问题，而且只能是Around方法中带注解参数才会出现这个问题。。。很尴尬，只要keep住就没问题。
