### ISSUE TITLE
与ARouter路由框架在同一个module一起使用时有问题

### ISSUE THREAD

**Issue by yeoggc** [HujiangTechnology/gradle_plugin_android_aspectjx#116]
导致ARouter注解处理器生成的类文件，没有打包到APK中，导致路由时产生there is no route match the path错误。 问题是为什么会导致类似ARouter$$Group$$main这样的文件没有打包到APK。

**Comment by firefly1126** [comment]
问一下你使用的`aspectjx`哪个版本。我使用`aspectjx 2.0.2`版本集成ARouter, 能正常编译，运行时功能正常，经测试`Aspectjx`功能正常，可以参考[整合了ARouter的Demo](https://github.com/HujiangTechnology/AspectJX-Demo)

**Comment by yeoggc** [comment]
最近比较忙，等周末的时候我在仔细的看看，到时在回复您
