### ISSUE TITLE
compile依赖改成implementation

### ISSUE THREAD

**Issue by xuqinqin2016** [HujiangTechnology/gradle_plugin_android_aspectjx#118]
能把源码中里面的compile依赖改成implementation或者api吗？现在编译的时候都有提示“WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.”

**Comment by zhoutianling** [comment]
同问

**Comment by githubshenxiaodong** [comment]
同问

**Comment by fy310518** [comment]
同问

**Comment by firefly1126** [comment]
`2.0.4`版本解决了这个问题
