### ISSUE TITLE
EOCD signature not found in the last 0 bytes of the file

### ISSUE THREAD

**Issue by GrowUpBoy** [HujiangTechnology/gradle_plugin_android_aspectjx#123]
Caused by: java.io.IOException: EOCD signature not found in the last 0 bytes of the file.

android studio 3.2
**project biuld.garlde:**
classpath 'com.android.tools.build:gradle:3.0.1'
classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.4'

**app biuld.garlde:**
apply plugin: 'com.hujiang.android-aspectjx'

**lib:**
implementation 'org.aspectj:aspectjrt:1.8.9'

**gradle-wrapper:**
distributionUrl=https://services.gradle.org/distributions/gradle-4.1-all.zip

**Comment by ohdroid** [comment]
> Try to clean and rebuild your project. It would be ok.

**Not working**

**Comment by GrowUpBoy** [comment]
not work , rebuild fail...  show the error again

**Comment by ohdroid** [comment]
> not work , rebuild fail... show the error again

I  tried to run with the demo program, make sure the syntax is correct, re-import to the existing project and it's working.

**Comment by KwanTang324** [comment]
rebuild no work
restart studio no work

**Comment by KwanTang324** [comment]
重启、重构都不行

**Comment by larrySmile02** [comment]
check your is your  method public .
检查一下被注释的方法是否public 

@Around(xxxxxx)
public void foo(JointPoint jp){
      ...
}
如果方法是private就会报错。
