### ISSUE TITLE
Cause: zip file is empty

### ISSUE THREAD

**Issue by lvzesong** [HujiangTechnology/gradle_plugin_android_aspectjx#126]
* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.JarClassFileInput$JarClassFileInputsException: Unable to read jar file /Users/xxx/AndroidStudioProjects/miaoup/app/build/intermediates/transforms/ajx/debug/61.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

**Comment by firefly1126** [comment]
你gradle版本多少，Android插件版本多少，是否使用了exclude 过滤配置？

**Comment by ganeshpadhayay** [comment]
Has anyone found a solution for this? I am stuck on this for days now
