### ISSUE TITLE
请问下，inculde 的规则是过滤包名所在的 module 吗？

### ISSUE THREAD

**Issue by whistlexie** [HujiangTechnology/gradle_plugin_android_aspectjx#127]
插件版本： classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.4'
gradle 版本：4.4   
gradle plugin 版本：3.1.3

app moudle的 build.gradle 配置如下

aspectjx {
    include 'com.yy.yylite.yyjspectj'
    include 'com.yy.yylite.live'
}

存在一个 library module 文件目录如下：
<img width="417" alt="3333" src="https://user-images.githubusercontent.com/10007354/47550724-b3076a80-d932-11e8-9978-51ca239baa90.png">

mainfest 文件如下：<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.yy.yylite.live" />

 <manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.yy.yylite.live" />

然后打印出来的结果如下：
10-26 15:17:50.593 21338-21338/com.yy.yylite.apsectjdoing V/LibraryTest: ⇠ DebugLog-libraryTest [50ms]
10-26 15:17:50.654 21338-21338/com.yy.yylite.apsectjdoing V/KotlonTest: ⇠ DebugLog-kotlinTest [60ms]
10-26 15:17:50.744 21338-21338/com.yy.yylite.apsectjdoing V/MsgTest: ⇠ DebugLog-testMsg [26ms]

也就是这里对 MsgTest.java  也进行了切面，请问可以通过配置过滤掉某个 module 中的某些文件吗？现在看起来 include 和 exclude 会把包名相关的全部过滤或者包含。

然后我尝试了以下配置：
aspectjx {
    include 'com.yy.yylite.yyjspectj'
    include 'com.yy.yylite.live'
    exclude 'om.yy.yylite.msg'
}
这会发现，live module 下全部文件切面都不生效了（在生成的 debug.apk 的 class 文件中，没看到切面代码）

过滤规则代码是在这里吗？
[(https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx/blob/master/aspectjx/src/main/groovy/com/hujiang/gradle/plugin/android/aspectjx/internal/procedure/CacheInputFilesProcedure.groovy)]
 @Override
    boolean doWorkContinuously() {
        //过滤规则
        //
        // "*" 所有class文件和jar
        // "**" 所有class文件和jar
        // "com.hujiang" 过滤 含"com.hujiang"的文件和jar
        //
        println "~~~~~~~~~~~~~~~~~~~~cache input files"
        BatchTaskScheduler taskScheduler = new BatchTaskScheduler()

        transformInvocation.inputs.each { TransformInput input ->
            input.directoryInputs.each { DirectoryInput dirInput ->
                variantCache.includeFileContentTypes = dirInput.contentTypes
                variantCache.includeFileScopes = dirInput.scopes

                taskScheduler.addTask(new ITask() {
                    @Override
                    Object call() throws Exception {
                        dirInput.file.eachFileRecurse { File item ->
                            if (AJXUtils.isClassFile(item)) {
                                String path = item.absolutePath
                                String subPath = path.substring(dirInput.file.absolutePath.length())
                                String transPath = subPath.replace(File.separator, ".")

                                boolean isInclude = AJXUtils.isIncludeFilterMatched(transPath, ajxExtensionConfig.includes) &&
                                        !AJXUtils.isExcludeFilterMatched(transPath, ajxExtensionConfig.excludes)
                                variantCache.add(item, new File((isInclude ? variantCache.includeFilePath : variantCache.excludeFilePath) + subPath))
                            }
                        }

                        //put exclude files into jar
                        if (AJXUtils.countOfFiles(variantCache.excludeFileDir) > 0) {
                            File excludeJar = transformInvocation.getOutputProvider().getContentLocation("exclude", variantCache.contentTypes,
                                    variantCache.scopes, Format.JAR)
                            AJXUtils.mergeJar(variantCache.excludeFileDir, excludeJar)
                        }

                        return null
                    }
                })
            }

麻烦大神有空指点一下，不胜感激。

**Comment by firefly1126** [comment]
`include`,`exclude`用于过滤第三方依赖的库，一旦规则匹配成功，整个jar都会生效。因为你的`om.yy.yylite.live`及`om.yy.yylite.msg`在同一个library module里面，所以根据你的规则会被全部排除掉。这种情况下你可以这样解决：
* 把 `om.yy.yylite.msg`放到一个独立的library module里去
* 在你的切面代码里面把`om.yy.lite.msg`排除掉，可以尝试用`!within()`试试。
