### ISSUE TITLE
引入Ant打包的jar后编译报错

### ISSUE THREAD

**Issue by luguosheng** [HujiangTechnology/gradle_plugin_android_aspectjx#13]
Error:Execution failed for task ':app:transformClassesWithAspectTransformForDebug'.

> Cannot read debug info for @Aspect to handle formal binding in pointcuts (please compile with 'javac -g' or '<javac debug='true'.../>' in Ant)

我写了一个带@Aspect的jar包加入工程中，如果是用IDE Export的jar包，就可以正常编译且aspect生效。现在我想用Ant给部分代码混淆，重新生成jar以后，编译时就出现了以上这个错误。

**Comment by firefly1126** [comment]
你的错误信息提示很清楚了，用‘javac -g’。建议用gradle处理代码混淆的问题，不要用Ant。
