### ISSUE TITLE
混淆打包问题

### ISSUE THREAD

**Issue by runcow** [HujiangTechnology/gradle_plugin_android_aspectjx#130]
1.release打包开了混淆，已经keep住了要切入的代码，还是提示zip is empty
2.debug包都正常
3.在app build.gradle 添加 
aspectjx {
        include '包名.**'
    }
以后可以正常打release包，但是切面不生效

请问哪里出了问题？

**Comment by firefly1126** [comment]
不是混淆的问题，和混淆无关，切面代码不需要keep。把切面代码的package include进去看看

**Comment by runcow** [comment]
解决了，是混淆的问题，但不是aspectjx的问题。自己工程混淆配置没有做对。
