### ISSUE TITLE
插件里面的gradle版本能从2.14.1升到4.1么

### ISSUE THREAD

**Issue by githubliangzai** [HujiangTechnology/gradle_plugin_android_aspectjx#131]
![image](https://user-images.githubusercontent.com/12453412/48112952-a6203a80-e293-11e8-8f3b-586a7e3eb3f7.png)

**Comment by githubliangzai** [comment]
![image](https://user-images.githubusercontent.com/12453412/48115435-d8cf3080-e29d-11e8-9693-2283231a9ba2.png)
gradle tool的版本能提升到3.0以上么

**Comment by firefly1126** [comment]
可以
