### ISSUE TITLE
我之前写的插件是用*.aj文件的，是可以插入代码的，后来改成你们的插件，用注解的形式，一直无法插入。

### ISSUE THREAD

**Issue by galaxybruce** [HujiangTechnology/gradle_plugin_android_aspectjx#134]
这是我的代码
`@Aspect
public class KWStatistics {

    @After(value = "call(* *.*KisListener(..))")
    public void doAllListener(JoinPoint joinPoint) {
        String typeName = getTypeName(joinPoint);
        String methodName = getMethodPathName(joinPoint);

        CodeSignature codeSignature = (CodeSignature) joinPoint.getSignature();
        String[] parameterNames = codeSignature.getParameterNames();
        Object[] parameterValues = joinPoint.getArgs();

        String param = null;
        for (int i = 0; i < parameterNames.length; i++) {
            String name = parameterNames[i];
            if("param".equals(name))
            {
                param = parameterValues[i] != null ? parameterValues[i].toString() : null;
                break;
            }
        }

        reportEvent(typeName, methodName, param);
    }

    @Before(value="execution(private void reportPagePoint(boolean))")
    public void doOnPage(JoinPoint joinPoint) {
        android.util.Log.i("aaaaaaaaaaaa", "KWStatistics.doOnPage : ");

        if(joinPoint.getArgs() == null || joinPoint.getArgs().length == 0) {
            return;
        }
        boolean open = (boolean)(joinPoint.getArgs()[0]);
        reportPage(joinPoint, open);
    }
}
`

java代码：
`  @Override
    protected void kwReportPointOnResume() {
        super.kwReportPointOnResume();
        reportPagePoint(true);
    }

    @Override
    protected void kwReportPointOnPause() {
        super.kwReportPointOnPause();
        reportPagePoint(false);
    }
    
    private void reportPagePoint(boolean open) {
    }`

**Comment by firefly1126** [comment]
注解写错了，`execution(private void reportPagePoint(boolean))`，这个方法找不到匹配。
