### ISSUE TITLE
gralde4.1下打包报错，java.io.IOException:Failed to read zip file

### ISSUE THREAD

**Issue by githubliangzai** [HujiangTechnology/gradle_plugin_android_aspectjx#135]
![image](https://user-images.githubusercontent.com/12453412/48413348-6a4d0f80-e782-11e8-8166-bad04ba14339.png)
![image](https://user-images.githubusercontent.com/12453412/48413372-7b961c00-e782-11e8-8963-ad5f3800b34f.png)
大神能帮忙看下么

**Comment by ban54** [comment]
> ![image](https://user-images.githubusercontent.com/12453412/48413348-6a4d0f80-e782-11e8-8166-bad04ba14339.png)
> ![image](https://user-images.githubusercontent.com/12453412/48413372-7b961c00-e782-11e8-8963-ad5f3800b34f.png)
> 大神能帮忙看下么

我也碰到这个问题了，最后找到原因是我代码语法写错了，普通方法@Around("execution(* com.sensorsdata.analytics.android.sdk.SensorsDataAPI.assertPropertyTypes(..))") 这儿的*忘了加上，你可以试试从这个角度看能找到问题原因不。

**Comment by firefly1126** [comment]
最好能把编译日志完整导出，看AOP过程中是否发生了异常，一般这种异常都会有日志的
