### ISSUE TITLE
Unable to read jar file

### ISSUE THREAD

**Issue by KKaKa** [HujiangTechnology/gradle_plugin_android_aspectjx#136]
gradle-4.1-all
com.android.tools.build:gradle:3.0.1
com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.0

```
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.JarClassFileInput$JarClassFileInputsException: Unable to read jar file F:\ProgressButton\app\build\intermediates\transforms\ajx\debug\29.jar
````
不支持4.4我降低为4.1后依旧不行，尝试手动删除build文件夹依旧不行。

**Comment by ban54** [comment]
我也碰到这个问题了，最后找到原因是我代码语法写错了，普通方法@Around("execution(* com.sensorsdata.analytics.android.sdk.SensorsDataAPI.assertPropertyTypes(..))") 这儿的*忘了加上，你可以试试从这个角度看能找到问题原因不。

**Comment by ban54** [comment]
> gradle-4.1-all
> com.android.tools.build:gradle:3.0.1
> com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.0
> 
> ```
> Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> > com.android.build.api.transform.TransformException: com.android.builder.dexing.JarClassFileInput$JarClassFileInputsException: Unable to read jar file F:\ProgressButton\app\build\intermediates\transforms\ajx\debug\29.jar
> ```
> 不支持4.4我降低为4.1后依旧不行，尝试手动删除build文件夹依旧不行。

我也碰到这个问题了，最后找到原因是我代码语法写错了，普通方法@Around("execution(* com.sensorsdata.analytics.android.sdk.SensorsDataAPI.assertPropertyTypes(..))") 这儿的*忘了加上，你可以试试从这个角度看能找到问题原因不。

**Comment by firefly1126** [comment]
多查看编译日志吧，一般AOP的错误会有日志的
