### ISSUE TITLE
配置 include 后无法进入aop

### ISSUE THREAD

**Issue by haohongxian77** [HujiangTechnology/gradle_plugin_android_aspectjx#138]

**Comment by haohongxian77** [comment]
1.在不分包的情况下没问题
2.在分包的时候，有java.lang.NoClassDefFoundError
3.然后添加了
aspectjx {
    include 'cn.com.nio.fellow.splash.*',
            'cn.com.nio.fellow.zxing.*'
}
但是发现切片进不去了...

**Comment by haohongxian77** [comment]
![image](https://user-images.githubusercontent.com/6087104/49058102-75ea0d00-f23d-11e8-94eb-c800bfd46b96.png)

**Comment by whistlexie** [comment]
出现了同样的问题~

**Comment by haohongxian77** [comment]
@whistlexie 咋解决

**Comment by whistlexie** [comment]
我也不知道

**Comment by haohongxian77** [comment]
没有解决...
