### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class

### ISSUE THREAD

**Issue by haohongxian77** [HujiangTechnology/gradle_plugin_android_aspectjx#139]
基础common lib 包中写aop,common 已分包，然后 在主工程当中引用,直接使用common中的aop注解没有问题。

在lib b中引用common,然后主工程当中引用lib b,b中使用了aop注解，b不分包没有问题，
一旦lib b分包就会出现上述问题。

这怎么解，有遇到的吗，请赐教不胜感激
@firefly1126 @luosheng @azone @rarnu @hiessu

**Comment by haohongxian77** [comment]
![image](https://user-images.githubusercontent.com/6087104/49140557-81b5fc00-f32f-11e8-8c80-1a810c105ca4.png)

**Comment by firefly1126** [comment]
信息不完整，不能帮你定位到问题。
