### ISSUE TITLE
support the gradle android plugin 2.2

### ISSUE THREAD

**Issue by JiangDaYa0** [HujiangTechnology/gradle_plugin_android_aspectjx#14]
java.lang.NoClassDefFoundError: com/android/builder/signing/SignedJarBuilder$IZipEntryFilter
        at com.hujiang.gradle.plugin.android.aspectjx.AspectTransform.transform(AspectTransform.groovy:147)

这个类在plugin 2.2中已经不再提供了

**Comment by firefly1126** [comment]
1.0.8版本解决了Android plugin 兼容性问题

依赖：
com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.0.8
