### ISSUE TITLE
Databind error

### ISSUE THREAD

**Issue by zzxzzg** [HujiangTechnology/gradle_plugin_android_aspectjx#18]
Error:Execution failed for task ':aspectjx-demo:transformClassesWithAspectTransformForDebug'.

> can't determine superclass of missing type android.support.v7.widget.CardView
>   when weaving type android.databinding.adapters.CardViewBindingAdapter
>   when weaving classes 
>   when weaving 
>   when batch building BuildConfig[null] #Files=0 AopXmls=#0
>    [Xlint:cantFindType]

**Comment by zzxzzg** [comment]
aspectjx {
        //织入遍历符合条件的库
        //includeJarFilter 'universal-image-loader', 'AspectJX-Demo/library'
        //排除包含‘universal-image-loader’的库
        excludeJarFilter 'databinding'
    }

发现添加以上过滤可以解决错误 0.0

**Comment by firefly1126** [comment]
很好，自己解决问题。后面aspectjx会默认忽略这类意义不大的编译警告和错误，这样就不需要配置过滤参数了

**Comment by zzxzzg** [comment]
instant run 什么时候能兼容 ？ 这是现在阻止我将aspectjx用在项目中的最大阻碍

**Comment by zzxzzg** [comment]
instant run 什么时候能兼容 ？ 这是现在阻止我将aspectjx用在项目中的最大阻碍

**Comment by zzxzzg** [comment]
instant run 什么时候能兼容 ？ 这是现在阻止我将aspectjx用在项目中的最大阻碍

**Comment by firefly1126** [comment]
正在解决，后续版本会加上
