### ISSUE TITLE
Cause: zip file is empty

### ISSUE THREAD

**Issue by 555chy** [HujiangTechnology/gradle_plugin_android_aspectjx#181]
classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.4'
apply plugin: 'com.hujiang.android-aspectjx'
implementation 'org.aspectj:aspectjrt:1.8.14'

Caused by: java.util.zip.ZipException: zip file is empty

大神，求原因啊。卡了一天了

**Comment by 54wall** [comment]
我是因为@Around后边写错了，导致找不到包，
aspectjx:2.0.4
androidstudio:3.4.0
android tools:3.4.0
gradle:5.1.1
https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx/issues/147

**Comment by 555chy** [comment]
对，我也是这个问题，自己语法写错了！谢谢。
（我发现在AspectJ里面，不管是语法还是语句写错了，就会导致各种诡异的错误）

**Comment by hongpp** [comment]
我是和Google的包冲突了，
aspectjx {
    exclude 'com.google'
}
就解决了

**Comment by CelebrateG** [comment]
> 我是和Google的包冲突了，
> Aspectjx {exclude'com.google 
> ' 
> } 
> 就解决了

怎么看出来冲突的

**Comment by CelebrateG** [comment]
> 我是和Google的包冲突了，
> Aspectjx {exclude'com.google 
> ' 
> } 
> 就解决了

怎么看出来冲突的
