### ISSUE TITLE
Getting classpath error: unable to find org.aspectj.lang.JoinPoint when running instrumentation tests

### ISSUE THREAD

**Issue by kirillzh** [HujiangTechnology/gradle_plugin_android_aspectjx#19]
Getting this error message when running instrumentation tests (`androidTest`) both in my project and in [AspectJX-Demo](https://github.com/HujiangTechnology/AspectJX-Demo) project:
```
Execution failed for task ':app:transformClassesWithAspectTransformForDebugAndroidTest'.
> classpath error: unable to find org.aspectj.lang.JoinPoint (check that aspectjrt.jar is in your classpath)

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithAspectTransformForDebugAndroidTest'.
```

**Comment by firefly1126** [comment]
check that your dependencies contains 
`compile 'org.aspectj:aspectjrt:1.8.9'`

**Comment by kirillzh** [comment]
My dependencies contain AspectJ. And as I said, I'm getting same error in
your demo project.

**Comment by huangying812** [comment]
it seem that,not  compatible with instant run.
i encounter the same  problem.foud that demo can build release apk,but when deploy debug version to real phone or emulor,it's just not work. then i turn off instant run,it fix!

**Comment by A-Zaiats** [comment]
When I run instrumental tests on my CI server, I have the same error. There is no instant run.

**Comment by rohankapoor** [comment]
Facing this on CI server. Instant run is not involved

**Comment by firefly1126** [comment]
version 1.0.10 has solved this problem. It can support AndroidTest
