### ISSUE TITLE
AS编译错误transformClassesWithJarMergingForDebug

### ISSUE THREAD

**Issue by vigossjjj** [HujiangTechnology/gradle_plugin_android_aspectjx#2]
我的环境是OSX + AS 2.1 release + jdk 1.7 + gradle 2.10 执行demo会报`transformClassesWithJarMergingForDebug`

日志如下：
![c2d6402d-3dda-421d-9862-f7f94add31db](https://cloud.githubusercontent.com/assets/4637829/15416336/ca5096f8-1e7c-11e6-8a87-6fb23a09a956.jpg)

**Comment by firefly1126** [comment]
这个是Android studio的Instant run 的一个Bug，在设置里关闭Instant run 功能可以正常编译。而且这种情况下在terminal下用命令编译是没问题的。
![instant_run](https://cloud.githubusercontent.com/assets/3377613/15447835/8830069a-1f81-11e6-8bef-2f3603e94b90.png)

**Comment by vinci2015** [comment]
gradle 插件 2.2.0 以上就会报错

**Comment by xwSurfer** [comment]
@vigossjjj 你的解决了吗，我的也存在这个问题
```
Execution failed for task ':Youku_Mobile:transformClassesWithJarMergingForAppstoreDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/aspectj/internal/lang/annotation/ajcDeclareAnnotation.class
```

instant run 已经关闭，用命令行编译也存在一样的问题。

**Comment by firefly1126** [comment]
1.0.8版本解决了Android 插件2.2.0的兼容性问题

**Comment by LLL-Luo** [comment]
Gradle Version               2.14.1
Android Plugin Version  2.2.3
关了instant run ；

1.1.0 版本有这问题存在； 后面配置 aspectjx {    includeJarFilter   ‘...’     } 解决的

**Comment by iRYO400** [comment]
@LLL-Luo hey mate!
what should I put inside **includeJarFilter**? Turning off instant run doesn't help
