### ISSUE TITLE
transformClassesWithExtractJarsForDebug

### ISSUE THREAD

**Issue by xuexin** [HujiangTechnology/gradle_plugin_android_aspectjx#20]
Error:Execution failed for task ':app:transformClassesWithExtractJarsForDebug'.
> error
新建project,只修改了两个build.gradle,clean不报错,运行时提示这个
环境:
AS 2.2.3
compileSdkVersion 25
buildToolsVersion "25.0.2"
classpath 'com.android.tools.build:gradle:2.2.3'
classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.0.8'

**Comment by xuexin** [comment]
ok,没注意已经有人提了一样的issue,关掉instant run之后解决了,请问有解决instant run不兼容的计划吗?

**Comment by LiushuiXiaoxia** [comment]
确实与Instant run不兼容

[https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx/issues/2](https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx/issues/2)

**Comment by xujinyang** [comment]
![image](https://cloud.githubusercontent.com/assets/4199903/22063459/eb59095a-ddb9-11e6-869d-171b2eeca797.png)

这个问题有人遇到过吗？

**Comment by firefly1126** [comment]
在1.0.8及以下版本 可以加配置过滤掉没法扫描植入代码的模块，如：
```
aspectjx {
    excludeJarFilter 'butterknife'
}
```

在最新的1.0.9版本默认加入了xlint警告忽略，不需要配置不会出现`can't determine superclass of missing type xxx`等类似错误了。

另外，关于Instant run的兼容问题及jack & jill 编译器兼容问题会在后续版本解决。

谢谢你的提问。
