### ISSUE TITLE
transformClassesWithAspectTransformForDebug fail

### ISSUE THREAD

**Issue by battleAgain** [HujiangTechnology/gradle_plugin_android_aspectjx#21]
![image](https://cloud.githubusercontent.com/assets/2534144/22110859/3e847ee6-de98-11e6-94fe-059a445cd9f7.png)

**Comment by firefly1126** [comment]
log日志里面已经说了，Android上的aspectj版本不支持`@DeclareAnnotation`

**Comment by huli1987** [comment]
解决了，Android上的aspectj版本不支持@DeclareAnnotation只是个警告，真正的错误时那个ClassFormatException，clean一下就好了

**Comment by chenxihoulang** [comment]
Error:Execution failed for task ':presentation_teachers:transformClassesWithAspectTransformForDebug'.
> trouble in: 
public class io.netty.handler.codec.protobuf.ProtobufEncoderNano extends io.netty.handler.codec.MessageToMessageEncoder:
    public void <init>():
                      ALOAD_0     // Lio/netty/handler/codec/protobuf/ProtobufEncoderNano; this   (line 60)
                      INVOKESPECIAL io.netty.handler.codec.MessageToMessageEncoder.<init> ()V
      constructor-execution(void io.netty.handler.codec.protobuf.ProtobufEncoderNano.<init>())
      |               RETURN
      constructor-execution(void io.netty.handler.codec.protobuf.ProtobufEncoderNano.<init>())
    end public void <init>()
    protected void encode(io.netty.channel.ChannelHandlerContext, com.google.protobuf.nano.MessageNano, java.util.List) throws java.lang.Exception:
                      ALOAD_2     // Lcom/google/protobuf/nano/MessageNano; msg   (line 64)
                      INVOKEVIRTUAL com.google.protobuf.nano.MessageNano.getSerializedSize ()I
                      ISTORE 4
                      ALOAD_1     // Lio/netty/channel/ChannelHandlerContext; ctx   (line 65)
                      INVOKEINTERFACE io.netty.channel.ChannelHandlerContext.alloc ()Lio/netty/buffer/ByteBufAllocator;
                      ILOAD 4     // I size
                      ILOAD 4     // I size
                      INVOKEINTERFACE io.netty.buffer.ByteBufAllocator.heapBuffer (II)Lio/netty/buffer/ByteBuf;
                      ASTORE 5
                      ALOAD 5     // Lio/netty/buffer/ByteBuf; buffer   (line 66)
                      INVOKEVIRTUAL io.netty.buffer.ByteBuf.array ()[B
                      ASTORE 6
                      ALOAD 6     // [B array   (line 67)
                      ALOAD 5     // Lio/netty/buffer/ByteBuf; buffer
                      INVOKEVIRTUAL io.netty.buffer.ByteBuf.arrayOffset ()I
                      ALOAD 5     // Lio/netty/buffer/ByteBuf; buffer
                      INVOKEVIRTUAL io.netty.buffer.ByteBuf.capacity ()I
                      INVOKESTATIC com.google.protobuf.nano.CodedOutputByteBufferNano.newInstance ([BII)Lcom/google/protobuf/nano/CodedOutputByteBufferNano;
                      ASTORE 7
                      ALOAD_2     // Lcom/google/protobuf/nano/MessageNano; msg   (line 69)
                      ALOAD 7     // Lcom/google/protobuf/nano/CodedOutputByteBufferNano; cobbn
                      INVOKEVIRTUAL com.google.protobuf.nano.MessageNano.writeTo (Lcom/google/protobuf/nano/CodedOutputByteBufferNano;)V
                      ALOAD 5     // Lio/netty/buffer/ByteBuf; buffer   (line 70)
                      ILOAD 4     // I size
                      INVOKEVIRTUAL io.netty.buffer.ByteBuf.writerIndex (I)Lio/netty/buffer/ByteBuf;
                      POP
                      ALOAD_3     // Ljava/util/List; out   (line 71)
                      ALOAD 5     // Lio/netty/buffer/ByteBuf; buffer
                      INVOKEINTERFACE java.util.List.add (Ljava/lang/Object;)Z
                      POP
                      RETURN   (line 72)
    end protected void encode(io.netty.channel.ChannelHandlerContext, com.google.protobuf.nano.MessageNano, java.util.List) throws java.lang.Exception
    protected volatile void encode(io.netty.channel.ChannelHandlerContext, Object, java.util.List) throws java.lang.Exception:
                      ALOAD_0     // Lio/netty/handler/codec/protobuf/ProtobufEncoderNano; this   (line 59)
                      ALOAD_1
                      ALOAD_2
                      CHECKCAST com.google.protobuf.nano.MessageNano
                      ALOAD_3
                      INVOKEVIRTUAL io.netty.handler.codec.protobuf.ProtobufEncoderNano.encode (Lio/netty/channel/ChannelHandlerContext;Lcom/google/protobuf/nano/MessageNano;Ljava/util/List;)V
                      RETURN
    end protected volatile void encode(io.netty.channel.ChannelHandlerContext, Object, java.util.List) throws java.lang.Exception
  end public class io.netty.handler.codec.protobuf.ProtobufEncoderNano
