### ISSUE TITLE
为什么Hook的类不能混淆呢？

### ISSUE THREAD

**Issue by battleAgain** [HujiangTechnology/gradle_plugin_android_aspectjx#22]
如题，如果我想hook应用内所有try catch语句中的 catch代码块，那不是整个应用都无法混淆了么；另外，我理解这种方案其实就是在编译期将advice注入到代码中，和字节码注入有点类似，只要是在混淆之前注入的，按理说应该混淆了页没关系啊

**Comment by firefly1126** [comment]
**Hook的类是可以混淆**

其实你的分析是正确的，因为代码是在编译阶段植入，所以混淆是不会有影响的，只有在运行时你需要通过类名，方法名去做一些事情的时候才不能混淆，比如你用到了反射技术等。所以你的情况应该是其他问题导致。

再次强调一下
* 任何在编译阶段植入代码的AOP方案混淆都不会受影响，和混淆无关。
* 任何运行时的AOP技术方案混淆都会受影响，比如xposed框架，dexposed框架。

**Comment by huli1987** [comment]
谢谢解答，另外，请问一下，我测试往BaseActivity的onCreate中注入了一行日志；编译出的apk能正确打印这行日志，但是我看编译后的class文件，为什么onCreate方法里看不到我注入方法的调用呢？

**Comment by LiushuiXiaoxia** [comment]
class里面是没有的，你看下`app/build/intermediates/transforms/AspectTransform ` 目录，然后找到对应的文件夹，里面有jar文件，反编译jar文件，就有对应注入的代码

**Comment by kasogg** [comment]
那为什么readme里面写的，需要在AOP代码进行hook的类及方法名不能被混淆,需要在混淆配置里keep住
