### ISSUE TITLE
java.lang.NoSuchMethodError: aspectOf

### ISSUE THREAD

**Issue by xyls09** [HujiangTechnology/gradle_plugin_android_aspectjx#23]
运行android_permission_aspectjx时报错：
java.lang.NoSuchMethodError: com.firefly1126.permissionaspect.aspect.PermissionAspect.aspectOf

**Comment by xyls09** [comment]
将permissionaspect中的java问价拷到app中就可以运行，不知道为什么在permissionaspect中时就报上述错误

**Comment by firefly1126** [comment]
动态权限这个库很久没有同步更新了，和我们内部使用的库有些差别，后面安排时间同步一下。

`aspectOf`这个方法是aspectj编译时生成的方法，出现这种情况一般是因为permissionaspect文件没有被aspectj编译进去。可能的原因是加入了过滤配置过滤掉了。可以解开../build/intermediates/transforms/AspectTransform/../aspected.jar查看编译后的代码结构。

**Comment by xyls09** [comment]
怎么把它编译进去呢，能否提供思路？

**Comment by firefly1126** [comment]
`Android_Permission_AspectjX`项目的app的build.gradle里面加了过滤把permissionaspect过滤了，这个配置有问题，去掉这个配置就OK了

```
aspectjx {
    jarFilter 'com.firefly1126.permissionaspect/permissionaspect'
}
```

**Comment by xyls09** [comment]
确实可以了，非常感谢您的回复

**Comment by zhouchaohong1111** [comment]
我的项目也出现了
java.lang.NoSuchMethodError: No static method aspectOf()Lcom/../../aop/LifeCycleAspect  
使用了最新的
classpath "com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.0.10"

**Comment by romii88** [comment]
同样遇到这个问题，使用了最新版本的plugin。
