### ISSUE TITLE
readme文档中的引用方式好像写错了

### ISSUE THREAD

**Issue by CB2Git** [HujiangTechnology/gradle_plugin_android_aspectjx#231]
应该是
classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.6'

classpath 'com.github.franticn:gradle_plugin_android_aspectjx:2.0.6'这个一直无法引用

**Comment by firefly1126** [comment]
已修正，多谢，这个是合并其他伙伴提交的PR，不慎引入的问题。
