### ISSUE TITLE
Android 如何混淆

### ISSUE THREAD

**Issue by VipMinF** [HujiangTechnology/gradle_plugin_android_aspectjx#24]
混淆后就不工作了，请问这个如何混淆

**Comment by firefly1126** [comment]
aspectjx本身和混淆没有关系，出现这种情况应该是你的代码里使用到了类似反射的技术。

另外你问的问题太宽泛，没法下手给具体的解决方案。如果有人问你`我这边出现了崩溃，请问怎么办？`请问你会怎么回答他？

**Comment by VipMinF** [comment]
感谢你的回答，我能明白你的意思，我知道混淆会影响反射。目前，我还没写一些实质的代码，只是按照例子中的DebugTool 代码完全一样，除了包名不同，因为是复制到项目中改了包名。出现的情况是，Debug版本是可以正常执行的，但是Release就不行了，出现的原因是注解引起的
