### ISSUE TITLE
update gradle tools 3.6.0

### ISSUE THREAD

**Issue by aheven** [HujiangTechnology/gradle_plugin_android_aspectjx#243]
when i update gradle tools 3.6.0，it's run error.
this is error msg：
`Cannot cast object 'com.android.build.gradle.internal.pipeline.TransformTask$2$1@35560a46' with class 'com.android.build.gradle.internal.pipeline.TransformTask$2$1' to class 'com.android.build.gradle.internal.pipeline.TransformTask'`

**Comment by AifeiI** [comment]
It should be com.android.tools.build:gradle appears after upgrading to version 3.6.0, it is not affected before version 3.5.3.

Possible fixes on com.android.tools.build:gradle:3.6.0:

[AJXTransform L68-L69](https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx/blob/master/aspectjx/src/main/groovy/com/hujiang/gradle/plugin/android/aspectjx/AJXTransform.groovy#L68-L69)
***before***:
```java
TransformTask transformTask = (TransformTask)transformInvocation.context
VariantCache variantCache = new VariantCache(ajxProcedure.project, ajxProcedure.ajxCache, transformTask.variantName)
```

***after***: 
```java
String variantName = transformInvocation.getContext().getVariantName()
VariantCache variantCache = new VariantCache(ajxProcedure.project, ajxProcedure.ajxCache, variantName)
```

@firefly1126

**Comment by r17171709** [comment]
可以发一个版本出来吗？

**Comment by aheven** [comment]
> 可以发一个版本出来吗？

我自己编译了插件，然后运行成功，由于不是作者，所以没办法发布到依赖库里，只能等待作者有空的时候更新...

**Comment by lucers** [comment]
> 我自己编译了插件，然后运行成功，由于不是作者，所以没办法发布到依赖库里，只能等待作者有空的时候更新...
可以请教一下怎么自己编译插件么?

**Comment by lucers** [comment]
可以请教一下怎么编译插件么?

**Comment by EthanCo** [comment]
请问一下，要编译这个插件的话，Android Studio要用什么版本 ?

**Comment by lucers** [comment]
先降到3.5.3吧,3.6暂时不行

**Comment by aheven** [comment]
> 请问一下，要编译这个插件的话，Android Studio要用什么版本 ?

对Android Studio版本没有太大要求，用升级后的3.6版本就可以了

**Comment by aheven** [comment]
> 么编译插

我有编译好的，如果你想学习编译插件，可以搜索gradle插件开发

**Comment by EthanCo** [comment]
@aheven 嗯嗯，我编译插件成功了，用的IDEA，十分感谢

**Comment by jianshengd** [comment]
![图片](https://user-images.githubusercontent.com/19710981/77139279-5de07180-6ab0-11ea-952e-af1efb81a352.png)
怎么编译，没用过。连识别都没成功

**Comment by Wudelin** [comment]
> @aheven 嗯嗯，我编译插件成功了，用的IDEA，十分感谢

请问是把这个项目拉下去，然后直接运行编译Task吗

**Comment by aheven** [comment]
> 我编译插件成功了，用的IDEA，十

不是的，你还需要配置插件开发的环境，包括groovy运行环境，gradle tools库

**Comment by baolw** [comment]
> > 我编译插件成功了，用的IDEA，十
> 
> 不是的，你还需要配置插件开发的环境，包括groovy运行环境，gradle tools库

想问下自己可以通过什么编辑出支持3.6的吗，关键点在哪里

**Comment by aheven** [comment]
> > > 我编译插件成功了，用的IDEA，十
> > 
> > 
> > 不是的，你还需要配置插件开发的环境，包括groovy运行环境，gradle tools库
> 
> 想问下自己可以通过什么编辑出支持3.6的吗，关键点在哪里

关键点在于二楼的解决方案，修改AJXTransform L68-L69代码

**Comment by firefly1126** [comment]
2.0.10版本已支持 3.6

**Comment by ChaosOctopus** [comment]
> 2.0.10版本已支持 3.6

Default interface methods are only supported starting with Android N (--min-api 24): void org.aspectj.lang.ProceedingJoinPoint.stack$AroundClosure(org.aspectj.runtime.internal.AroundClosure)

**Comment by parcool** [comment]
Default interface methods are only supported starting with Android N (--min-api 24): void org.aspectj.lang.ProceedingJoinPoint.stack$AroundClosure(org.aspectj.runtime.internal.AroundClosure)
