### ISSUE TITLE
aspectjrt 对应的表达式在哪里看的?

### ISSUE THREAD

**Issue by gunC** [HujiangTechnology/gradle_plugin_android_aspectjx#25]
org.aspectj:aspectjrt 对应的表达式在哪里可以看的?谢谢

**Comment by LiushuiXiaoxia** [comment]
什么表达式？

**Comment by gunC** [comment]
应叫  [AspectJ 切入点语法](http://blog.csdn.net/kjfcpua/article/details/7513273).
