### ISSUE TITLE
编译报错: Cannot cast...

### ISSUE THREAD

**Issue by InnocentYang** [HujiangTechnology/gradle_plugin_android_aspectjx#276]
![image](https://user-images.githubusercontent.com/5811977/89515861-42c99080-d80a-11ea-80a5-5435af314f35.png)

新建的Module，语言选择Java，没有选择Kotlin，
其他Module有用Kotlin。
没有添加AspectJ相关的代码。

project.build.gradle中
`dependencies {
    classpath 'com.android.tools.build:gradle:4.0.1'
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72"
    classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.8'
}`

module.build.gradle中
`apply plugin: 'com.android.application'
apply plugin: 'android-aspectjx'`
dependency中没有添加 api aspectj

gradle/wrapper/gradle-wrapper.properties中
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip`

编译时报错：
Cannot cast object 'com.android.build.gradle.internal.pipeline.TransformTask$2$1@2999f666' with class 'com.android.build.gradle.internal.pipeline.TransformTask$2$1' to class 'com.android.build.gradle.internal.pipeline.TransformTask'

完全没有头绪，不知道该怎么处理。

**Comment by crazyzhangxl** [comment]
Gradle版本过高，你可以使用3.6.1 => 2.0.10

**Comment by InnocentYang** [comment]
修改版本后，编译正常。

**Comment by hezhipengzipp** [comment]
要做兼容呀
