### ISSUE TITLE
java.util.zip.ZipException: zip file is empty

### ISSUE THREAD

**Issue by Quyunshuo** [HujiangTechnology/gradle_plugin_android_aspectjx#282]
一直是这个问题 新建项目 引入插件  编写简单的代码  就跑不了  弄了一天  也没跑起来

**Comment by Quyunshuo** [comment]
我的解决方案是只对当前包切面 
aspectjx {
    include '需要切面的包'
}

**Comment by juanyueer** [comment]
> 我的解决方案是只对当前包切面
> aspectjx {
> include '需要切面的包'
> }

我参考你的方案只对当前我切面，但是应用启动的时候就crash了。不知道楼主这边的配置是什么样的
