### ISSUE TITLE
Error:Execution failed for task ':app:transformClassesWithAspectTransformForFullDebug'.

### ISSUE THREAD

**Issue by happywilma** [HujiangTechnology/gradle_plugin_android_aspectjx#30]
Error:Execution failed for task ':app:transformClassesWithAspectTransformForFullDebug'.
> trouble in: 
  public class com.eg.odk.client.utils.NameValuePairComparator extends java.lang.Object implements java.util.Comparator:
    public void <init>():
                      ALOAD_0     // Lcom/eg/odk/client/utils/NameValuePairComparator; this   (line 14)
                      INVOKESPECIAL java.lang.Object.<init> ()V
      constructor-execution(void com.eg.odk.client.utils.NameValuePairComparator.<init>())
      |               RETURN
      constructor-execution(void com.eg.odk.client.utils.NameValuePairComparator.<init>())
    end public void <init>()
    public int compare(org.apache.http.NameValuePair, org.apache.http.NameValuePair):
                      ALOAD_1     // Lorg/apache/http/NameValuePair; lhs   (line 17)
                      INVOKEINTERFACE org.apache.http.NameValuePair.getName ()Ljava/lang/String;
                      ALOAD_2     // Lorg/apache/http/NameValuePair; rhs
                      INVOKEINTERFACE org.apache.http.NameValuePair.getName ()Ljava/lang/String;
                      INVOKEVIRTUAL java.lang.String.compareTo (Ljava/lang/String;)I
                      IRETURN
    end public int compare(org.apache.http.NameValuePair, org.apache.http.NameValuePair)
    public volatile int compare(Object, Object):
                      ALOAD_0     // Lcom/eg/odk/client/utils/NameValuePairComparator; this   (line 14)
                      ALOAD_1     // Ljava/lang/Object; x0
                      CHECKCAST org.apache.http.NameValuePair
                      ALOAD_2     // Ljava/lang/Object; x1
                      CHECKCAST org.apache.http.NameValuePair
                      INVOKEVIRTUAL com.eg.odk.client.utils.NameValuePairComparator.compare (Lorg/apache/http/NameValuePair;Lorg/apache/http/NameValuePair;)I
                      IRETURN
    end public volatile int compare(Object, Object)
  end public class com.eg.odk.client.utils.NameValuePairComparator

 com.eg.odk 是引用的第三方包

**Comment by sixgodIT** [comment]
@happywilma 请问你的问题如何解决的，我现在定义了多个flavors，打包也出现类似的错误：transformClassesWithAspectTransformForTestDebug
