### ISSUE TITLE
特定环境编译异常：zip file is empty

### ISSUE THREAD

**Issue by JooperGe** [HujiangTechnology/gradle_plugin_android_aspectjx#300]
基本配置：
AndroidStudio 4.1.1
aspectjx 2.0.10
gradle 4.1.0

编译异常配置：
kotlin 1.4.10

编译正常配置：
kotlin 1.3.72

**Comment by zfhuang-cn** [comment]
kotlin 1.4.10里加了个META-INF/versions/9/module-info.class，可以使用配置的方式把他排除掉
```
aspectjx {
    exclude 'versions.9'
}
```
