### ISSUE TITLE
java.lang.NoSuchMethodError: No static method aspectOf()

### ISSUE THREAD

**Issue by JohnsonJLi** [HujiangTechnology/gradle_plugin_android_aspectjx#301]
ext.kotlin_version = "1.4.10"

classpath "com.android.tools.build:gradle:4.1.1"
classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.10'

aspectjx {
    enabled true
     exclude 'androidx', 'com.google', 'com.squareup', 'org.apache', 'versions.9'
}

**Comment by JohnsonJLi** [comment]
替换成 
aspectjx {
include '包名', '包名'
}
可以用  但不知道有没有什么问题

**Comment by JohnsonJLi** [comment]
我把 exclude 'androidx'  去掉 好像 就没有问题了

**Comment by jammychan** [comment]
在写aspectjx的类，增加aspectOf()方法。例如为TestAop：
public static TestAop aspectOf() {
    return new TestAop();
}

**Comment by milesleeknight** [comment]
> lugin-aspectjx:2.0.10'
> 
> aspectjx { enabled true exclude 'androidx', 'com.google', 'com.squareup', 'org.apache', 'versions.9' }

java.lang.IncompatibleClassChangeError:
![image](https://user-images.githubusercontent.com/18733006/163514352-71d32350-7604-4d31-8e81-0a5a7abf1be2.png)
加上之后报错这个，请问有碰到过吗
