### ISSUE TITLE
构建多个变种耗时一直在递增

### ISSUE THREAD

**Issue by wurensen** [HujiangTechnology/gradle_plugin_android_aspectjx#305]
![image](https://user-images.githubusercontent.com/11225172/100427321-3f198c80-30cd-11eb-8ca1-62243bcad0f2.png)
 
如图，项目中目前kotlin和java混编，发现每次同时打多变种时ajx任务耗时一直在增加，构建是否并行都试过，都很耗时。
aspectj版本：2.0.6
AGP：3.3.3
gradle：gradle-4.10.2
android studio：4.0.2

**Comment by wurensen** [comment]
禁用调apsectj插件后就正常

**Comment by wurensen** [comment]
![image](https://user-images.githubusercontent.com/11225172/100437949-81969580-30dc-11eb-92c1-e106ce6820e1.png)

原因应该找到了：transformer一次构建任务只有一个实例，但是transform会根据变种个数多次执行，图中ajxProcedure在每次变种执行的时候，with函数会添加越来越多的procedure，导致变种越多，构建时间越来越长。

**Comment by RunningShadow-007** [comment]
遇到了同样的问题

**Comment by wurensen** [comment]
@RunningShadow-007 看下近期会不会修复，不然准备fork先改个版本了，到时候提个pr，但是看最近一条pr也很久没动静了。

**Comment by wurensen** [comment]
已自己修复：https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx/issues/332
