### ISSUE TITLE
Error:Execution failed for task ':aweme:transformClassesWithAspectTransformForDebug'. > ABORT

### ISSUE THREAD

**Issue by SparrowC** [HujiangTechnology/gradle_plugin_android_aspectjx#31]
ABORT
org.aspectj.weaver.BCException: Whilst processing type 'Lcom/squareup/haha/guava/collect/Iterables$2;' - cannot cast the outer type to a reference type.  Signature=Lcom/squareup/haha/guava/collect/Iterables; toString()=com.squareup.haha.guava.collect.Iterables class=Iterables
when processing type mungers 
when weaving 
when batch building BuildConfig[null] #Files=0 AopXmls=#0

**Comment by SparrowC** [comment]
忽略所有的.jar文件就好了
aspectjx {
	excludeJarFilter '.jar'
}

**Comment by louiewh** [comment]
那个文件添加呢？
