### ISSUE TITLE
gradle 4.1.1 not supported

### ISSUE THREAD

**Issue by StrugglingAndroid** [HujiangTechnology/gradle_plugin_android_aspectjx#310]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithAjxForDebug'.
> Cannot cast object 'com.android.build.gradle.internal.pipeline.TransformTask$2$1@7b849f6e' with class 'com.android.build.gradle.internal.pipeline.TransformTask$2$1' to class 'com.android.build.gradle.internal.pipeline.TransformTask'

**Comment by AfterFinal** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithAjxForDebug'.
> Cannot cast object 'com.android.build.gradle.internal.pipeline.TransformTask$2$1@7b849f6e' with class 'com.android.build.gradle.internal.pipeline.TransformTask$2$1' to class 'com.android.build.gradle.internal.pipeline.TransformTask'

**Comment by TheMelody** [comment]
是androidX其他的库版本高了，目前只能等他们升级了，androidX的部分库不要升级到最新的

**Comment by StrugglingAndroid** [comment]
buildscript {
    repositories {
        maven {
            url "https://jitpack.io"
        }
    }
    dependencies {
        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.4'
        //classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.10' //for newer gradle version ex:4.x
    }
}

**Comment by hezhipengzipp** [comment]
gradle-5.6.4  gradle-android-plugin-aspectjx:2.0.8 也不支持呀
