### ISSUE TITLE
什么时候支持下Agp 4.x ?

### ISSUE THREAD

**Issue by niniloveyou** [HujiangTechnology/gradle_plugin_android_aspectjx#315]

**Comment by dupengyun** [comment]
不要使用这个项目了，后期维护是一堆坑

**Comment by niniloveyou** [comment]
是的，太坑了这玩意，时不时就冲突以下，和其他插桩冲突，和热修冲突，AGP不兼容，说多了都是泪

**Comment by wurensen** [comment]
@niniloveyou 我现在fork过来改来维护了，可以关注我的：https://github.com/wurensen/gradle_plugin_android_aspectjx
我项目目前AGP使用4.1.3没有问题，你具体AGP版本是多少？下一步我适配一下
