### ISSUE TITLE
有人遇到打成Release包，AOP框架不生效的问题嘛？

### ISSUE THREAD

**Issue by SixGL** [HujiangTechnology/gradle_plugin_android_aspectjx#318]
代码都没有织入（Debug包没问题）  感觉是混淆问题。  这个插件怎么配置混淆？
```
-keep class org.aspectj.*.** {*;}
-keep class com.hujiang.gradle.plugin.android.*.** {*;}
这样吗
```

**Comment by yuchangliang** [comment]
你是怎么解决的，我也遇到了，只要开启 minifyEnabled true，就不生效。

**Comment by cxMax** [comment]
有遇到，不过感觉不是混淆的问题， 我们项目中有引用arouter和robust， assembleDebug，如果配置混淆，能正常织入。但是如果使用assembleRelease就无法织入了
