### ISSUE TITLE
可以对JDK的一些源码进行静态织如吗？

### ISSUE THREAD

**Issue by TonyW92** [HujiangTechnology/gradle_plugin_android_aspectjx#32]
比如我想修改java.net.Socket这个文件可以吗
谢谢！

**Comment by yxy1217** [comment]
@TonyW92  问下，这个问题你已经解决了吗？

**Comment by TonyW92** [comment]
@yxy1217 静态织入无解，只能修改打包的文件，就是项目的源码和第三方代码 可是试试动态织入aspect
