### ISSUE TITLE
java.util.zip.ZipException: zip file is empty

### ISSUE THREAD

**Issue by TheMelody** [HujiangTechnology/gradle_plugin_android_aspectjx#324]
Hello, after using the **gradle_plugin_android_aspectjx** libary, when building the apk, the following problem occurred:
```java
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> java.lang.RuntimeException: java.util.zip.ZipException: zip file is empty
```

Please help to solve this problem. Currently, many of the latest libraries cannot be integrated and upgraded normally.

**Comment by andrepeng** [comment]
我也遇到了同样的问题

**Comment by kirin233x** [comment]
只把你自己需要的东西在aspectx {
   include xxx
}
其他不需要的不要加。

**Comment by dupengyun** [comment]
不要使用这个项目了，作者已经不更新了，后期使用一堆坑。早弃早脱坑

**Comment by TheMelody** [comment]
> 只把你自己需要的东西在aspectx {
> include xxx
> }
> 其他不需要的不要加。

不行的哦，是现在的第三方的一些开源库都在升级，如果集成最新的GSON或者用了最新的leakcannary等等第三方的库都无法正常打包

**Comment by wurensen** [comment]
> 坑

真的是这样，要么自己fork改，要么弃坑。

**Comment by wurensen** [comment]
> 不要使用这个项目了，作者已经不更新了，后期使用一堆坑。早弃早脱坑
真的是这样，要么fork自己改，要么脱坑～

**Comment by wurensen** [comment]
> 不要使用这个项目了，作者已经不更新了，后期使用一堆坑。早弃早脱坑

真的是这样，要么fork自己维护，要么脱坑～

**Comment by wurensen** [comment]
可以使用我修复的版本：https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx/issues/332
