### ISSUE TITLE
遇到过@Aspect不起作用

### ISSUE THREAD

**Issue by xyls09** [HujiangTechnology/gradle_plugin_android_aspectjx#34]
被@Aspect注解过的类，反编译后正常情况下会有以下代码，现在没有了，报找不到AdviceProcessor.aspectOf()错误，不知道什么原因会造成该现象。

private static Throwable ajc$initFailureCause;
  public static final AdviceProcessor ajc$perSingletonInstance;

  static
  {
    try
    {
      ajc$postClinit();
      return;
    }
    catch (Throwable localThrowable)
    {
      ajc$initFailureCause = localThrowable;
    }
  }

  private static void ajc$postClinit()
  {
    ajc$perSingletonInstance = new AdviceProcessor();
  }

  public static AdviceProcessor aspectOf()
  {
    if (ajc$perSingletonInstance == null)
      throw new NoAspectBoundException("com.qiangqu.shandiangou.apptrace.annotation.AdviceProcessor", ajc$initFailureCause);
    return ajc$perSingletonInstance;
  }

  public static boolean hasAspect()
  {
    return ajc$perSingletonInstance != null;
  }

**Comment by firefly1126** [comment]
出现这种情况是因为被`@Aspectj`标记的代码被过滤掉了，没有被aspectjx处理到，可能是aspectjx的过滤配置影响到了，尝试删除它试试：
```
aspectjx {
    includeJarFilter ''
   excludeJarFilter ''
}
```
