### ISSUE TITLE
与其他 Transform 插件一起使用存在问题

### ISSUE THREAD

**Issue by darktiny** [HujiangTechnology/gradle_plugin_android_aspectjx#35]
#### 1. aspectjx 依赖 JarInput 的路径来作过滤
当 aspectjx 不是第一个被应用时，JarInput 的路径（举个例子：excludeJar:::/Users/.../.../app/build/intermediates/transforms/.../alpha/jars/1/10/e57ebac67c347bc2985e94932aa28dc58f848c3c.jar）无法作为判断条件，可能导致 aspectjx 找不到需要处理的文件

#### 2. aspectjx 插件把多个输入的 Jar 和 Dir 合并成了一个
导致其他插件的可能无法正常执行 [Transform JavaDoc](http://google.github.io/android-gradle-dsl/javadoc/current/)
> It is best practice to write into as many outputs as Jar/Folder Inputs have been received by the transform. Combining all the inputs into a single output prevents downstream transform from processing limited scopes.

[Related Issue](https://github.com/evant/gradle-retrolambda/issues/189)

**Comment by firefly1126** [comment]
谢谢提议，这个隐患之前考虑过，后面会考虑细化到class文件级别的粒度去查找需要AOP的文件

**Comment by xingshen** [comment]
已经自定义了Transform插件，就没有办法兼容了吗？
