### ISSUE TITLE
针对android studio里，provided方式引入的第三方库，编译出错，应该怎么处理

### ISSUE THREAD

**Issue by yujiaolong** [HujiangTechnology/gradle_plugin_android_aspectjx#37]
Error:Execution failed for task ':app:transformClassesWithAspectTransformForDebug'.
> can't determine modifiers of missing type com.yjl.test.external
when weaving type com.qihoo.apmsdkdemo.MainActivity
when weaving classes 
when weaving 
when batch building BuildConfig[null] #Files=2 AopXmls=#0
 [Xlint:cantFindType]

错误如上所示
missing的类（ com.yjl.test.external）是在jar包里，但是这个jar包是provided的方式引入的，如果不做aop是可以编译通过的，但是加上aop之后，就无法编译通过，不知道这个如何处理
我用provided方式引入jar的的场景是想调用系统不公开的api，比如PackageParser

**Comment by firefly1126** [comment]
目前没有解决provided的问题
