### ISSUE TITLE
ASM error

### ISSUE THREAD

**Issue by fabianbergmark** [HujiangTechnology/gradle_plugin_android_aspectjx#38]
this is some of my app gradle file:

buildscript {
    repositories {
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'org.aspectj:aspectjtools:1.8.10'
        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.0.11'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'android-aspectjx'

However, I get the following error, why?

org.aspectj.weaver.BCException: Unable to find Asm for stackmap generation (Looking for 'aj.org.objectweb.asm.ClassReader'). Stackmap generation for woven code is required to avoid verify errors on a Java 1.7 or higher runtime

**Comment by firefly1126** [comment]
Did you compile your project with Java 9? If so, degrade to Java 8.
