### ISSUE TITLE
插入aspectjx配置

### ISSUE THREAD

**Issue by guxiaonian** [HujiangTechnology/gradle_plugin_android_aspectjx#40]
您好，我想插入aspetcjx的时候，不插桩任何第三方包，下面这个配置需要在哪里面配置呢
aspectjx {
	excludeJarFilter '.jar'
}

**Comment by firefly1126** [comment]
在主项目的build.gradle最外层结构，可以参考[Demo](https://github.com/HujiangTechnology/AspectJX-Demo)

**Comment by kasogg** [comment]
加了excludeJarFilter '.jar'之后连自己项目里的插桩都不起作用了 @firefly1126
