### ISSUE TITLE
运行时间太慢了

### ISSUE THREAD

**Issue by HongJun2046** [HujiangTechnology/gradle_plugin_android_aspectjx#42]
因为你们现在使用的方式，是在lib里面不处理aspectj，在主工程处理，这样会导致会扫描所有包，虽然能用includeJar的方式，但是acpectj花费的时间还是要1分钟
你看这样可不可以，只在对应工程处理自己内部的aspectj，这样如果是aar或者maven依赖的话，就不用在扫描里面的了
还有你可以看看这个http://www.jianshu.com/p/814315922353，看看有没有可以吸取的思想，提高编译速度

**Comment by firefly1126** [comment]
谢谢你的建议，这是个很好的建议，编译效率的问题之前一直在考虑，由于最近比较忙，一直没有来得及实施，但是会在未来的版本里实现编译提速。你提供的这篇文章的博主dim是饿了么的工程师，他也曾是AspectJX的contributor，他在AspectJX 的基础上做出的优化和改进，是很不错的尝试。
