### ISSUE TITLE
can't determine superclass of missing type xxx

### ISSUE THREAD

**Issue by haofei91** [HujiangTechnology/gradle_plugin_android_aspectjx#46]
`Error:Execution failed for task ':app:transformClassesWithAspectTransformForDevDebug'.
> can't determine superclass of missing type android.hardware.fingerprint.FingerprintManager$AuthenticationCallback
when weaving type android.support.v4.hardware.fingerprint.FingerprintManagerCompatApi23$1
when weaving classes 
when weaving 
when batch building BuildConfig[null] #Files=0 AopXmls=#0
 [Xlint:cantFindType]`

我的目录结构最开始为：
---app
---aspjx1
其中app中也有切面编程的东西，此时打包是正常的

我就想把app中的切面编程移除来，变成：
---app
---aspjx1
---aspjx2
然后就报上述错误了

**Comment by firefly1126** [comment]
如果你想将切面代码放在独立的module里，请参考[AspectJX-Demo](https://github.com/HujiangTechnology/AspectJX-Demo)的做法
