### ISSUE TITLE
apply plugin: 'android-aspectjx' 编译问题

### ISSUE THREAD

**Issue by koukoucai** [HujiangTechnology/gradle_plugin_android_aspectjx#47]
在编译过程中
![image](https://user-images.githubusercontent.com/4627549/28766742-7a6d5628-7603-11e7-8dc3-362634a9130a.png)
出现了以上问题。
苦逼的回滚代码和多次编译尝试后发现是build.gradle中apply plugin: 'android-aspectjx'和 该jar包发生冲突。
这个jar包混淆编译输出时未配置-dontusemixedcaseclassnames 导致同个包名下生成了ABCD和abcd类。
导致以上问题。
但是奇怪的是
`aspectjx {
    excludeJarFilter '.jar'
}`
我已经添加上述选项，应该已经排除掉所有jar包了的。
为何还会抱截图问题呢，咨询下up主。

**Comment by firefly1126** [comment]
出现编译的问题，请提供如下内容以便我更好的帮你定位问题：
* 你项目编译的grale版本是多少
* 你使用的的Android plugin版本是多少
* 详细的错误日志

**Comment by firefly1126** [comment]
2.0.0做了重大调整，有更好的编译效率和稳定性，该版本做了如下调整：
* 支持Instant Run编译
* 废弃 includeJarFilter和excludeJarFilter两个配置命令
* 新增 include和 exclude配置命令，通过包名(package)路径关键字匹配，可过滤class文件和库文件(jar)
* include和 exclude配置命令支持*，**通配符
* 修复已知的gradle兼容性Bug
* 提升编译效率
* 解决 `Could not find matching constructor for: org.gradle.util.Clock()`
