### ISSUE TITLE
AOP定义防止连续点击，编译报错无法运行

### ISSUE THREAD

**Issue by UltramanTIGA** [HujiangTechnology/gradle_plugin_android_aspectjx#48]
代码：
@Aspect
public class SingleClickAspect {
    static int TIME_TAG = 10000;
    public static final int MIN_CLICK_DELAY_TIME = 600;

    @Around("execution(* android.view.View.OnClickListener.onClick(..))")
    public void aroundJoinPoint(ProceedingJoinPoint joinPoint) throws Throwable {
        View view = null;
        for (Object arg : joinPoint.getArgs())
            if (arg instanceof View) view = (View) arg;
        if (view != null) {
            Object tag = view.getTag(TIME_TAG);
            long lastClickTime = ((tag != null) ? (long) tag : 0);
            KLog.debug("SingleClickAspect", "lastClickTime:" + lastClickTime);
            long currentTime = Calendar.getInstance().getTimeInMillis();
            if (currentTime - lastClickTime > MIN_CLICK_DELAY_TIME) {//过滤连续点击
                view.setTag(TIME_TAG, currentTime);
                KLog.debug("SingleClickAspect", "currentTime:" + currentTime);
                joinPoint.proceed();
            }
        }
    }
}
报错信息：
Error:Execution failed for task ':app:transformClassesWithDexForAppDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
Error:1 error; aborting
Error:Uncaught translation error: com.android.dx.cf.code.SimException: local variable type mismatch: attempt to set or access a value of type java.lang.Object using a local variable of type int. This is symptomatic of .class transformation tools that ignore local variable information.
删除around定义的代码块后即可正常运行，clean和rebuild也试过，均无用。求助，谢谢

**Comment by ditclear** [comment]
我添加了这个，就可以了
aspectjx {
	excludeJarFilter '.jar'
}

**Comment by UltramanTIGA** [comment]
@ditclear 我试过，一样的。。。

**Comment by firefly1126** [comment]
2.0.0做了重大调整，有更好的编译效率和稳定性，该版本做了如下调整：
* 支持Instant Run编译
* 废弃 includeJarFilter和excludeJarFilter两个配置命令
* 新增 include和 exclude配置命令，通过包名(package)路径关键字匹配，可过滤class文件和库文件(jar)
* include和 exclude配置命令支持*，**通配符
* 修复已知的gradle兼容性Bug
* 提升编译效率
* 解决 `Could not find matching constructor for: org.gradle.util.Clock()`
