### ISSUE TITLE
comple error  Android studio 3.0 beta2 + gradle 4.1-rc-1 

### ISSUE THREAD

**Issue by fergus-fg** [HujiangTechnology/gradle_plugin_android_aspectjx#51]
`
* What went wrong:
Execution failed for task ':AspectApp:transformClassesWithDexBuilderForDebug'.
> Unexpected scopes found in folder '/home/fenggang/Desktop/AndridTips/AspectApp/build/intermediates/transforms/AspectTransform/debug'. Required: PROJECT, SUB_PROJECTS, EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, PROJECT_LOCAL_DEPS, SUB_PROJECTS, SUB_PROJECTS_LOCAL_DEPS

`

**Comment by fergus-fg** [comment]
not suppot `com.android.tools.build:gradle:3.0.0-beta2 `

**Comment by dumazy** [comment]
I'm having the same issue. Is there a work-around or will this be supported soon?
Thanks :+1:

**Comment by fergus-fg** [comment]
@dumazy  try `com.android.tools.build:gradle:2.3.3`

**Comment by dumazy** [comment]
downgrading was not an option for me. I eventually went with another AspectJ gradle plugin

**Comment by coofee** [comment]
@dumazy I have sloved this problem，you can try with pull-request code below.

https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx/pull/54

**Comment by Object-Ping** [comment]
I'm having the same issue. Is there a work-around or will this be supported soon?
Thanks 👍

**Comment by fergus-fg** [comment]
see [#54](https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx/pull/54)
