### ISSUE TITLE
现在的excludeJarFilter是以jar为单位的，粒度太粗。能否增加以类名或者包名为单位的exclude配置

### ISSUE THREAD

**Issue by wangxiaojingo** [HujiangTechnology/gradle_plugin_android_aspectjx#52]
是这样的：我想hook我们子工程中一个jar里面的一个类，但是include这个jar之后，会出现其中一个类superclass cantFindType的问题（因为这个jar编译的时候排除了一个类）；exclude这个jar就不能实现我的需求。

谢谢=。=

**Comment by wangxiaojingo** [comment]
看提交log发现1.0.11已经解决这个问题，升级版本号即可忽略Xlint，已解决

**Comment by firefly1126** [comment]
2.0.0做了重大调整，有更好的编译效率和稳定性，该版本做了如下调整：
* 支持Instant Run编译
* 废弃 includeJarFilter和excludeJarFilter两个配置命令
* 新增 include和 exclude配置命令，通过包名(package)路径关键字匹配，可过滤class文件和库文件(jar)
* include和 exclude配置命令支持*，**通配符
* 修复已知的gradle兼容性Bug
* 提升编译效率
* 解决 `Could not find matching constructor for: org.gradle.util.Clock()`
