### ISSUE TITLE
好像遇到NDK的class就没法weave？

### ISSUE THREAD

**Issue by xm0625** [HujiangTechnology/gradle_plugin_android_aspectjx#55]
没想过用改源码重新打包的方式实现吗？
比如这个?
https://github.com/vincentbernat/dashkiosk-android/blob/eaa36bf540f2e436e9ac9f7d257083470b7dd831/build.gradle

**Comment by firefly1126** [comment]
NDK 的class可以尝试用`call`的方式切入方法，不要用`execution`的方式。
