### ISSUE TITLE
配置了 excludeJarFilter '.jar' 还是能 hook 到 gms 库中的函数

### ISSUE THREAD

**Issue by ganyao114** [HujiangTechnology/gradle_plugin_android_aspectjx#56]
如题，不是以 jar 包导入的方式引进的库是不是不生效？

**Comment by TYUpya** [comment]
请问这个问题得到解决了吗？

**Comment by firefly1126** [comment]
不是这样的，所有的库本质上都是通过jar的方式依赖的，如果还是能hook 到 gms 库中的函数，你可以在excludeJarFilter 参数里直接配置gms依赖路径上的关键字。

**Comment by firefly1126** [comment]
2.0.0做了重大调整，有更好的编译效率和稳定性，该版本做了如下调整：
* 支持Instant Run编译
* 废弃 includeJarFilter和excludeJarFilter两个配置命令
* 新增 include和 exclude配置命令，通过包名(package)路径关键字匹配，可过滤class文件和库文件(jar)
* include和 exclude配置命令支持*，**通配符
* 修复已知的gradle兼容性Bug
* 提升编译效率
* 解决 `Could not find matching constructor for: org.gradle.util.Clock()`
