### ISSUE TITLE
【急】！！！一个很简单的问题。。。

### ISSUE THREAD

**Issue by TYUpya** [HujiangTechnology/gradle_plugin_android_aspectjx#58]
aspectjx {
	excludeJarFilter '.jar'
}

请问以上代码要写在哪个方法块中？我在说明中未找到详细例子。

**Comment by firefly1126** [comment]
写在最外层的build.gradle，可以参考Demo项目 https://github.com/HujiangTechnology/AspectJX-Demo

**Comment by TYUpya** [comment]
好的，谢谢 @firefly1126 ！

**Comment by VinaChiong** [comment]
@TYUpya 个人建议另外新建一个.gradle文件，例如aspectConfig.gradle。
里面apply plugin 并配置aspectjx代码。
在最外层的build.gradle通过 apply from引用该文件。

**Comment by TYUpya** [comment]
@VinaChiong 请问具体 你是怎么写的呢？ 能不能发个例子出来，谢谢！

**Comment by VinaChiong** [comment]
aspectConfig.gradle文件

> apply plugin: 'android-aspectjx'
> aspectjx
>  {
>       includeJarFilter ...
>       excludeJarFilter ....
> }

保存在项目根目录下, 或根目录下的相对路劲。

app的build.gradle

>apply plugin: 'com.android.application'
>apply from: rootProject.file('aspectConfig.gradle')
> ...
