### ISSUE TITLE
cannot work with android  studio 3 

### ISSUE THREAD

**Issue by davyjoneswang** [HujiangTechnology/gradle_plugin_android_aspectjx#59]
* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> Unexpected scopes found in folder '/Users/davy/CODE/Joshua/app/build/intermediates/transforms/AspectTransform/debug'. Required: PROJECT, SUB_PROJECTS, EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, PROJECT_LOCAL_DEPS, SUB_PROJECTS, SUB_PROJECTS_LOCAL_DEPS

**Comment by sniper52237** [comment]
一样的错误demo跑步起来，而且product下没有发现gradle-android-plugin-aspectjx-1.0.10.jar这个包

**Comment by meablelee2013** [comment]
the same question as you

**Comment by firefly1126** [comment]
2.0.0做了重大调整，有更好的编译效率和稳定性，该版本做了如下调整：
* 支持Instant Run编译
* 废弃 includeJarFilter和excludeJarFilter两个配置命令
* 新增 include和 exclude配置命令，通过包名(package)路径关键字匹配，可过滤class文件和库文件(jar)
* include和 exclude配置命令支持*，**通配符
* 修复已知的gradle兼容性Bug
* 提升编译效率
* 解决 `Could not find matching constructor for: org.gradle.util.Clock()`
