### ISSUE TITLE
Is the 'new' plugin in Maven repo?

### ISSUE THREAD

**Issue by onirtuen** [HujiangTechnology/gradle_plugin_android_aspectjx#6]
Hi, 

When i tried to import the 'deprecated' plugin as stated on this page: http://blog.egorand.me/going-aspect-oriented-with-aspectj-and-google-analytics/ it worked:

```
buildscript {  
    ...
    dependencies {
        ...
        classpath 'com.uphyca.gradle:gradle-android-aspectj-plugin:0.9.14'
    }
}

```

However if I try to use the new one like you mention in 'How to use' section: 
```
dependencies {
        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.0.5'
        }
```
gradle fails to find it. Looks like it's not there?

**Comment by firefly1126** [comment]
It's int [jcenter](http://jcenter.bintray.com/com/hujiang/aspectjx/gradle-android-plugin-aspectjx/1.0.5/)

Maybe you are blocked by the wall. Using VPN to access the jcenter.

Also you can using [jar] in this project ../product/..

**Comment by onirtuen** [comment]
Ouch, sorry I do use jcenter. I was able to use previous (deprecated) plugin and it worked great. If I try to use this one, gradle will complain that it can't find it.

**Comment by firefly1126** [comment]
Can this Demo project work?
https://github.com/HujiangTechnology/AspectJX-Demo

**Comment by onirtuen** [comment]
Yes, after changing ASDK version here and there I was able to build (incl. unit tests).
So probably something wrong with my configuration. I'll dig. Thanks!
