### ISSUE TITLE
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.

### ISSUE THREAD

**Issue by LineChen** [HujiangTechnology/gradle_plugin_android_aspectjx#60]
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> Unexpected scopes found in folder '/Users/chenliu/studyApp/HugoDemo/app/build/intermediates/transforms/AspectTransform/debug'. Required: PROJECT, SUB_PROJECTS, EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, PROJECT_LOCAL_DEPS, SUB_PROJECTS, SUB_PROJECTS_LOCAL_DEPS

**Comment by firefly1126** [comment]
use version 1.1.0 to compile your project

**Comment by LineChen** [comment]
@firefly1126 OK ，thank you

**Comment by lyx0224** [comment]
@firefly1126  not work! same error.

**Comment by guliangli** [comment]
我也遇到这个问题,求解

**Comment by chanthuang** [comment]
同样遇到这个问题，求解。
version 1.1.0 也同样 not work. same error.

**Comment by firefly1126** [comment]
2.0.0做了重大调整，有更好的编译效率和稳定性，该版本做了如下调整：
* 支持Instant Run编译
* 废弃 includeJarFilter和excludeJarFilter两个配置命令
* 新增 include和 exclude配置命令，通过包名(package)路径关键字匹配，可过滤class文件和库文件(jar)
* include和 exclude配置命令支持*，**通配符
* 修复已知的gradle兼容性Bug
* 提升编译效率
* 解决 `Could not find matching constructor for: org.gradle.util.Clock()`
