### ISSUE TITLE
我只想对自己项目里的代码进行插入，怎么配置啊

### ISSUE THREAD

**Issue by kasogg** [HujiangTechnology/gradle_plugin_android_aspectjx#62]
我的项目的包名是a.b
下面有若干个module
a.b.app（主module）
a.b.lib1（library module）
a.b.lib2（library module）
a.b.lib3（定义aspect的library module）

我只想对自己项目里的代码进行插入(所有a.b包下的，排除第三方的库)，怎么配置啊
excludeJarFilter ".jar" 和 includeJarFilter "a.b" 的话，插入都没效果

**Comment by VinaChiong** [comment]
> includeJarFilter,
 excludeJarFilter can support **groupId** filter, **artifactId** filter and **dependency path** matching.
仅仅包名应该是匹配不到的。

1.excludeJarFilter 'a.b.app/libs', ''a.b.lib1/libs''...  排除library module的libs目录下的jar
2.includeJarFilter 'a.b.app'

**Comment by firefly1126** [comment]
预计在1.1.1后面的版本会加入class文件级别的过滤支持

**Comment by firefly1126** [comment]
2.0.0做了重大调整，有更好的编译效率和稳定性，该版本做了如下调整：
* 支持Instant Run编译
* 废弃 includeJarFilter和excludeJarFilter两个配置命令
* 新增 include和 exclude配置命令，通过包名(package)路径关键字匹配，可过滤class文件和库文件(jar)
* include和 exclude配置命令支持*，**通配符
* 修复已知的gradle兼容性Bug
* 提升编译效率
* 解决 `Could not find matching constructor for: org.gradle.util.Clock()`
