### ISSUE TITLE
 It doesn't work when I use JavaVersion.VERSION_1_8 and :gradle:3.0.0

### ISSUE THREAD

**Issue by BigTimo** [HujiangTechnology/gradle_plugin_android_aspectjx#63]
buildscript {
...
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.1.0'//AOP
    }
...
}

android {
  ...
//use gradle3.0 , remove this option can work,but you can't use lambda.
    compileOptions { 
        sourceCompatibility JavaVersion.VERSION_1_8 
        targetCompatibility JavaVersion.VERSION_1_8
    }
...
}

=================================================================
**change gradle to 2.3.1  and use lambda,it can work;**
dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'
        classpath 'me.tatarka:gradle-retrolambda:3.4.0'//lambda
        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.1.0'//AOP
    }

**Comment by ganyao114** [comment]
https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx/issues/61

**Comment by firefly1126** [comment]
最近release的`1.1.1`版本解决了Java8的支持问题，但是这个版本如果用Java8编译，`includeJarFiter`, `excludeJarFilter`这两个过滤配置失效，配置问题会在下个版本修复。

**Comment by firefly1126** [comment]
2.0.0做了重大调整，解决了该问题，2.0.0有更好的编译效率和稳定性，该版本做了如下调整：
* 支持Instant Run编译
* 废弃 includeJarFilter和excludeJarFilter两个配置命令
* 新增 include和 exclude配置命令，通过包名(package)路径关键字匹配，可过滤class文件和库文件(jar)
* include和 exclude配置命令支持*，**通配符
* 修复已知的gradle兼容性Bug
* 提升编译效率
* 解决 `Could not find matching constructor for: org.gradle.util.Clock()`
