### ISSUE TITLE
请问这个插件如何依赖本地的AspectJ库

### ISSUE THREAD

**Issue by Lihengju1990** [HujiangTechnology/gradle_plugin_android_aspectjx#65]
由于我公司开发不连外网，我下了离线的aspectjrt 库,但是你的插件在运行会去联网下载依赖的aspectJ库,请问有什么办法可以依赖本地的aspectJrt库，很是困扰啊 帮下我

**Comment by firefly1126** [comment]
先把库下载在本地，让后用 `compile files('xxx')`的方式依赖进去就OK了
