### ISSUE TITLE
Could not find matching constructor for: org.gradle.util.Clock()

### ISSUE THREAD

**Issue by Tim1008** [HujiangTechnology/gradle_plugin_android_aspectjx#66]
环境：
classpath 'com.android.tools.build:gradle:3.0.1'
gradle版本4.3

TimeTrace.groovy类中 
`    @Override
    void beforeExecute(Task task) {
        clock = new Clock()
    }`
是不是要改为
`    @Override
    void beforeExecute(Task task) {
        clock = new Clock(new Date().getTime())
    }`

**Comment by TYUpya** [comment]
你可以使用Gradle版本4.1，就不会报错了。

**Comment by xiayifeng** [comment]
现在不然用4.1了，被as强制用4.4了，怎么办

**Comment by xiayifeng** [comment]
3.0.1最低4.4了gradle了，怎么解决

**Comment by V-zhangyunxiang** [comment]
发现了更好的解决方案了吗

**Comment by V-zhangyunxiang** [comment]
gradle 4.4 目前也会出现这个问题

**Comment by muja555** [comment]
I made a solution but I can't push it, it gives me: 
`Push failed: Failed with error: unable to access 'https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx.git/': The requested URL returned error: 403`

**Comment by firefly1126** [comment]
2.0.0版本解决了这个问题，另外2.0.0是一个重大版本，做了如下调整：
* 支持Instant Run编译
* 废弃 includeJarFilter和excludeJarFilter两个配置命令
* 新增 include和 exclude配置命令，通过包名(package)路径关键字匹配，可过滤class文件和库文件(jar)
* include和 exclude配置命令支持*，**通配符
* 修复已知的gradle兼容性Bug
* 提升编译效率
* 解决 `Could not find matching constructor for: org.gradle.util.Clock()`
