### ISSUE TITLE
什么时候能支持JAVA 1.8？ 希望尽快更新，谢谢！

### ISSUE THREAD

**Issue by TYUpya** [HujiangTechnology/gradle_plugin_android_aspectjx#67]
什么时候能支持JAVA 1.8？ 
lssues中有些人提出了解决方案，但是都是治标不治本。
希望尽快更新，谢谢！

**Comment by firefly1126** [comment]
最近release的`1.1.1`版本解决了Java8的支持问题，但是这个版本如果用Java8编译，`includeJarFiter`, `excludeJarFilter`这两个过滤配置失效，配置问题会在下个版本修复。

**Comment by TYUpya** [comment]
非常非常非常感谢 @firefly1126  您的付出。
但是由于项目的原因，我还是只能等待您解决了【includeJarFiter, excludeJarFilter这两个过滤配置失效】这个问题后再使用。谢谢！

**Comment by TYUpya** [comment]
@firefly1126  请问这个问题解决了吗？Has the problem been solved?

**Comment by firefly1126** [comment]
2.0.0版本解决了这个问题，做了如下调整：
* 支持Instant Run编译
* 废弃 includeJarFilter和excludeJarFilter两个配置命令
* 新增 include和 exclude配置命令，通过包名(package)路径关键字匹配，可过滤class文件和库文件(jar)
* include和 exclude配置命令支持*，**通配符
* 修复已知的gradle兼容性Bug
* 提升编译效率
* 解决 `Could not find matching constructor for: org.gradle.util.Clock()`
