### ISSUE TITLE
如何对android sdk的方法进行hook？

### ISSUE THREAD

**Issue by luguosheng** [HujiangTechnology/gradle_plugin_android_aspectjx#7]
我想对Activity中的performCreate(Bundle icicle)方法进行hook，可以实现么？

**Comment by firefly1126** [comment]
暂时不行，因为aspectjx现在暂时是通过静态代码织入的方式实现hook, performCreate在系统SDK里面，而且是final的，没法重载，所以做不了。动态hook的一些方案可以实现，比如xposed,dexposed，但是目前他们在各个Android系统上表现不稳定。

要实现对Android SDK里面的方法进行hook，必须先在自己的代码里重载该方法，比如onCreate方法。
