### ISSUE TITLE
android studio gradle 3.0.1  @Aspect 还是失效

### ISSUE THREAD

**Issue by zouxianbincc** [HujiangTechnology/gradle_plugin_android_aspectjx#71]
not a puppet object

**Comment by TYUpya** [comment]
请问这个问题解决了吗？Has the problem been solved?

**Comment by TYUpya** [comment]
请问这个问题解决了吗？Has the problem been solved?

**Comment by firefly1126** [comment]
问题描述不详，最好能提供全面的信息和log信息

**Comment by zhiwenyan** [comment]
classpath 'com.android.tools.build:gradle:3.1.1'
classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.1.0'  

build的时候 报以下错：
FAILURE: Build failed with an exception.
* What went wrong:
Could not find matching constructor for: org.gradle.util.Clock()

1.1.0还是不兼容

**Comment by weinierfei** [comment]
gradle版本使用4.1就可以了

**Comment by RavenHide** [comment]
gradle版本是4.1，build:gradle:3.0.1
报了这个错
Error:Execution failed for task ':app:transformClassesWithAspectTransformForDebug'.
> org/aspectj/bridge/MessageHandler
请问是什么问题

**Comment by weinierfei** [comment]
根目录的build.gradle文件中添加一个classpath 'org.aspectj:aspectjtools:1.8.9'

**Comment by RavenHide** [comment]
加了之后，又报这个错误

Error:Execution failed for task ':app:transformClassesWithExtractJarsForDebug'.
> Unexpected scopes found in folder 'E:\AndroidPlayground\TextAop\app\build\intermediates\transforms\AspectTransform\debug'. Required: SUB_PROJECTS. Found: EXTERNAL_LIBRARIES, PROJECT, SUB_PROJECTS

@weinierfei 请问是什么问题？ 使用的是gradle-android-plugin-aspectjx:1.1.0 版本，好像在这个版本是不会有这个问题的

**Comment by diov** [comment]
我看到[#75](https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx/pull/75)已经处理了这个问题，但是好像还没有发布新的 Gradle Plugin。
如果有需求应该自己 build 一下就行了

**Comment by firefly1126** [comment]
2.0.0版本解决了这个问题，另外2.0.0是一个重大版本，做了如下调整：
* 支持Instant Run编译
* 废弃 includeJarFilter和excludeJarFilter两个配置命令
* 新增 include和 exclude配置命令，通过包名(package)路径关键字匹配，可过滤class文件和库文件(jar)
* include和 exclude配置命令支持*，**通配符
* 修复已知的gradle兼容性Bug
* 提升编译效率
* 解决 `Could not find matching constructor for: org.gradle.util.Clock()`
