### ISSUE TITLE
Could not find matching constructor for: org.gradle.util.Clock()

### ISSUE THREAD

**Issue by nievita** [HujiangTechnology/gradle_plugin_android_aspectjx#79]
最新的1.1.0版本没有包含你修复的代码

**Comment by nievita** [comment]
[](url)

**Comment by nievita** [comment]
2个月前修改的代码没有包含在1.1.0版本中

**Comment by fuqiang915** [comment]
1.1.1版本中也没有,

**Comment by x930073498** [comment]
这个可以自己fork下来然后编译一下，如果图方便可以：classpath 'com.github.x930073498:gradle_plugin_android_aspectjx:v1.1.1.1'。
这个我没有改里面的代码，直接编译的。以后大神们出新的了再换回来即可。

**Comment by firefly1126** [comment]
2.0.0版本解决了这个问题，另外2.0.0是一个重大版本，做了如下调整：
* 支持Instant Run编译
* 废弃 includeJarFilter和excludeJarFilter两个配置命令
* 新增 include和 exclude配置命令，通过包名(package)路径关键字匹配，可过滤class文件和库文件(jar)
* include和 exclude配置命令支持*，**通配符
* 修复已知的gradle兼容性Bug
* 提升编译效率
* 解决 `Could not find matching constructor for: org.gradle.util.Clock()`
