### ISSUE TITLE
TransformException

### ISSUE THREAD

**Issue by qsmaxmin** [HujiangTechnology/gradle_plugin_android_aspectjx#83]
Error:java.io.IOException: Failed to read zip file '****\app\build\intermediates\transforms\ajx\ALiYun\debug\69.jar'.
Error:java.io.IOException: EOCD signature not found in the last 0 bytes of the file.
Error:Execution failed for task ':app:transformClassesWithDexBuilderForALiYunDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.JarClassFileInput$JarClassFileInputsException: Unable to read jar file ****\app\build\intermediates\transforms\ajx\ALiYun\debug\69.jar

**Comment by firefly1126** [comment]
问一下你使用的gradle版本多少，Android插件版本多少，据我所知` EOCD signature not found`的问题会在使用gradle 4.4版本的时候出现，gradle 4.4 版本改动比较大，暂时还没有做兼容，建议暂时先使用gradle 4.1, android插件3.0.1版本，后续兼容gradle4.4后再通知大家。

**Comment by wzbo** [comment]
1.检查 @Pointcut 切点是否存在
2.尝试修改切点名称

**Comment by imaiya** [comment]
我同样遇到了这个问题

**Comment by Xiasm** [comment]
我也遇到了这个问题

**Comment by dezng** [comment]
我在一个旧项目中遇到了这个问题，最后怀疑是使用了hugo导致，hugo 同样使用了 aspectj，最后在 build.gradle 中去掉 hugo 相关依赖，去掉代码中 hugo 相关的部分，就编过了。

在项目目录下使用了如下两个命令去掉 DebugLog 注解
```
find . -name "*.java" | xargs sed -r -i "s#(@DebugLog)#/*\1*/#"
find . -name "*.java" | xargs sed -ri "s#(import hugo.weaving.DebugLog;)#/*\1*/#"
```

**Comment by GrowUpBoy** [comment]
Caused by: java.io.IOException: EOCD signature not found in the last 0 bytes of the file.    
classpath 'com.android.tools.build:gradle:3.0.1'
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
4.1也不行
