### ISSUE TITLE
能编译,但是出了一堆error

### ISSUE THREAD

**Issue by yangqqq537** [HujiangTechnology/gradle_plugin_android_aspectjx#85]
Error:INVOKESPECIAL org.apache.http.impl.client.DefaultHttpClient.<init> (Lorg/apache/http/params/HttpParams;)V
Error:PUTFIELD com.alipay.sdk.net.b.c Lorg/apache/http/impl/client/DefaultHttpClient;
Error:INVOKESPECIAL org.apache.http.impl.client.DefaultHttpClient.<init> (Lorg/apache/http/conn/ClientConnectionManager;Lorg/apache/http/params/HttpParams;)V
Error:PUTFIELD com.alipay.sdk.net.b.c Lorg/apache/http/impl/client/DefaultHttpClient;
Error:GETSTATIC com.alipay.sdk.net.b.b Lcom/alipay/sdk/net/b;   (line 105)
Error:INVOKESPECIAL org.apache.http.params.BasicHttpParams.<init> ()V
Error:GETSTATIC org.apache.http.HttpVersion.HTTP_1_1 Lorg/apache/http/HttpVersion;
Error:INVOKESTATIC org.apache.http.params.HttpProtocolParams.setVersion (Lorg/apache/http/params/HttpParams;Lorg/apache/http/ProtocolVersion;)V
Error:INVOKESTATIC org.apache.http.params.HttpConnectionParams.setStaleCheckingEnabled (Lorg/apache/http/params/HttpParams;Z)V
Error:INVOKEINTERFACE org.apache.http.params.HttpParams.setBooleanParameter (Ljava/lang/String;Z)Lorg/apache/http/params/HttpParams;
Error:INVOKESTATIC org.apache.http.conn.params.ConnManagerParams.setMaxTotalConnections (Lorg/apache/http/params/HttpParams;I)V
Error:INVOKESPECIAL org.apache.http.conn.params.ConnPerRouteBean.<init> (I)V
Error:INVOKESTATIC org.apache.http.conn.params.ConnManagerParams.setMaxConnectionsPerRoute (Lorg/apache/http/params/HttpParams;Lorg/apache/http/conn/params/ConnPerRoute;)V
Error:INVOKESTATIC org.apache.http.conn.params.ConnManagerParams.setTimeout (Lorg/apache/http/params/HttpParams;J)V
Error:INVOKESTATIC org.apache.http.params.HttpConnectionParams.setConnectionTimeout (Lorg/apache/http/params/HttpParams;I)V

下面还有一堆error,项目是能跑,但是每次构建都会出现这些,基本都是org.apache.http里的,用了exclude(org.apache.http)也没用,build文件里就没这个包名文件

**Comment by firefly1126** [comment]
信息不全，无法很好的帮助你排查问题，建议补充：
1. gradle 版本信息
2. Android插件版本信息
3. aspectjx版本信息
4. 尽量完整的编译日志
