### ISSUE TITLE
手贱更新了AS  compile   有救吗？ 

### ISSUE THREAD

**Issue by tinynong** [HujiangTechnology/gradle_plugin_android_aspectjx#86]
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
 
报这个错  有办法没。。。

**Comment by firefly1126** [comment]
这个和gradle 版本，Android插件版本有关 
把gradle 设为4.1
Android插件版本3.0.1
这样`compile`还可以用

其实是有`implementation`, `api`也一样的

另外，这个问题和`aspectjx`无关

**Comment by tinynong** [comment]
哦哦。。  改下来就可以了。。  之前是加了aspectjx  就报错了   哈哈哈   太菜了太菜了    谢谢大佬解惑

**Comment by tinynong** [comment]
好像  kotlin的  不支持？
