### ISSUE TITLE
kotlin 配置

### ISSUE THREAD

**Issue by tinynong** [HujiangTechnology/gradle_plugin_android_aspectjx#88]
哥哥救我。。。

报错：  Multiple dex files define Lorg/aspectj/internal/lang/reflect/PerClauseImpl;

项目有高德地图  retrofit
还有就是aspectjx

model ：
`
 dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.0'
    }
`
app:
`
apply plugin: 'android-aspectjx'
...
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    implementation 'com.android.support:support-v4:26.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    //Retrofit2.0
    implementation 'com.squareup.retrofit2:retrofit:2.4.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.9.0'

    //高德地图相关
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    //3D地图so及jar
    implementation 'com.amap.api:3dmap:latest.integration'
    //定位功能
    implementation 'com.amap.api:location:latest.integration'
    //搜索功能
    implementation 'com.amap.api:search:latest.integration'

    //aspectj
    compile 'org.aspectj:aspectjrt:1.9.1'
}
`

**Comment by tinynong** [comment]
kotlin  写的规则无效吗？

**Comment by firefly1126** [comment]
先用Java写规则吧，kotlin写的规则目前不生效，有Bug，后续会尽快修复。
