### ISSUE TITLE
打包生成release版本切面无效，debug版本切面有用，求解决

### ISSUE THREAD

**Issue by LzzzzzzC** [HujiangTechnology/gradle_plugin_android_aspectjx#90]
project gradle配置如下
 dependencies {
classpath 'com.android.tools.build:gradle:3.1.2'  
classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.1'
classpath 'org.aspectj:aspectjtools:1.8.13'
}

**Comment by TechPursuer** [comment]
同求解

**Comment by HelloWorld-L** [comment]
release是不是加了混淆？ 我这边加了混淆切面就无效 把混淆去了就正常

**Comment by happyer2018** [comment]
一样的问题，怎么解决啊

**Comment by superxlcr** [comment]
我这边是把切面代码放在了一个单独的module里面，把混淆开关关掉就好了，不然好像是因为没有引用代码被proguard剪掉了

**Comment by TechPursuer** [comment]
//    if (!variant.buildType.isDebuggable()) {
//        log.debug("Skipping non-debuggable build type
'${variant.buildType.name}'.")
//        return;
//    }


*构建工程执行编译的时候，把上面代码注释即可*


superxlcr <notifications@github.com> 于2018年8月16日周四 下午7:54写道：

**Comment by happyer2018** [comment]
@TechPursuer 注释了那段代码，可以啦！
