### ISSUE TITLE
如何配置仅对某包名下的进行切面

### ISSUE THREAD

**Issue by winxinxinxin** [HujiangTechnology/gradle_plugin_android_aspectjx#98]
如何配置仅对某包名下的进行切面？
如下配置结果是排除所有
aspectjx {
    exclude '\*'
    include 'com.a.b.\*'
}

**Comment by Zhoucj1986** [comment]
把exclude去掉就好了。
这个配置的规则是，先include需要切面的包，再在这些包里exclude不需要的包。所以你的写法结果就是把所有的都exclude掉了。

**Comment by batsman2skip** [comment]
fike
